export { default as ErrorsList } from './admin/errorsList'
export { default as ErrorDetail } from './admin/errorDetail'
export { default as DashboardsPage } from './admin/dashboards'
export { default as AuthPage } from './auth'
export { default as MainPage } from './main'
